services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql:3306
      DB_NAME: biblioteca
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 7s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  mysql-data:
